title: "Bob Summerwill"
description: ""
url: "https://bobsummerwill.github.io"
baseurl: "/website"
permalink: /:year/:month/:day/:title/

# Pagination
paginate: 10
paginate_path: "/page/:num/"

# Build
markdown: kramdown
highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .github
  - README.md
  - CNAME

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# Author
author:
  name: "Bob Summerwill"
